language: node_js
node_js:
- '8'
directories:
- node_modules
before_install:
- mkdir -p  ~/.ssh/
- openssl aes-256-cbc -K $encrypted_09c5eaff0959_key -iv $encrypted_09c5eaff0959_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 123.207.252.230 \n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- cat ~/.ssh/config
install:
- npm install
before_script:
script:
- npm run build
after_script:
- cd ./${DIST_BRANCH}
- git init
- git config user.name "${U_NAME}"
- git config user.email "${U_EMAIL}"
- git add .
- git commit -m "${COMMIT_MSG}"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
after_success:
- cd ./${DIST_BRANCH}
- pwd
- tar -jcf vote.tar.bz2 *
- scp vote.tar.bz2 ubuntu@123.207.252.230:~/
- ssh ubuntu@123.207.252.230 'mkdir -p /usr/share/nginx/html/votes && mv ./vote.tar.bz2
  /usr/share/nginx/html/votes && cd /usr/share/nginx/html/votes && tar -jxf vote.tar.bz2
 && rm -rf vote.tar.bz2'
branches:
  only:
  - master
env:
  global:
